markdown: kramdown
title: tojamrok 
email: <16987182+tojamrok@users.noreply.github.com>
description: >- # this means to ignore newlines until "baseurl:"
    tojamrok blog
baseurl: "" # the subpath of your site, e.g. /blog
name: tojamrok blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /blog/:year/:month/:day/:title
logo: "assets/images/wyrak-small.jpg"
include: ["_pages"]

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives

jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'

paginate: 6
paginate_path: /page:num/

